language: python
python:
- 3.6
install:
- pip install tox
script:
- tox
deploy:
  provider: pages
  name: Travis CI
  email: simplivity-pythonsdk@hpe.com
  local_dir: docs/build/html/.
  skip_cleanup: true
  github_token: $SIMPLIVITY_DEPLOY_TOKEN
  keep_history: true
  on:
    branch: master

